input_features:
- type: number
  name: feature_1
  encoder:
    type: dense
    output_size: 64
- type: number
  name: feature_2
  encoder:
    type: dense
    output_size: 64
- type: number
  name: feature_3
  encoder:
    type: dense
    output_size: 64
combiner:
  type: transformer
  bias_initializer: zeros
  dropout: 0.2
  fc_activation: relu
  fc_dropout: 0
  fc_residual: false
  hidden_size: 64
  num_fc_layers: 0
  num_heads: 8
  num_layers: 5
  output_size: 64
  reduce_output: attention
  transformer_output_size: 256
  use_bias: true
  weights_initializer: xavier_uniform
defaults:
  number:
    preprocessing:
      normalization: zscore
trainer:
  epochs: 500
  early_stop: 200
  validation_field: assigned_label
  evaluate_training_set: true
  learning_rate: 0.0001
  batch_size: 128
  learning_rate_scheduler:
    warmup_evaluations: 5
  optimizer:
    type: adam
output_features:
- name: assigned_label
  type: number
  reduce_dependencies: sum
  reduce_input: sum
  preprocessing:
    computed_fill_value: 0
    fill_value: 0
    missing_value_strategy: drop_row
  loss:
    type: mean_squared_error
    weight: 1
  decoder:
    bias_initializer: zeros
    fc_activation: relu
    fc_bias_initializer: zeros
    fc_dropout: 0
    fc_output_size: 256
    fc_use_bias: true
    fc_weights_initializer: xavier_uniform
    num_fc_layers: 2
    type: regressor
    use_bias: true
    weights_initializer: xavier_uniform
backend:
  type: ray
  processor:
    type: dask
  trainer:
    strategy: horovod
