input_features:
  -
    name: overview
    type: text
    level: word
    encoder: bert
    tied_weights: null
    pretrained_model_name_or_path: bert-base-uncased
    reduce_output: cls_pooled
    trainable: false
  -
    name: genres
    type: set
  -
    name: production_companies
    type: set
  -
    name: production_countries
    type: set
  -
    name: release_year
    type: numerical
  -
    name: user_id
    type: text
  -
    name: movie_id
    type: text

output_features:
  -
    name: rating
    type: numerical

training:
  epochs: 10
  early_stop: 3

