input_features:
  - name: sentence
    type: text
    encoder: transformer
    layers: 6
    embedding_size: 512

output_features:
  - name: class
    type: category
    loss:
      type: softmax_cross_entropy
      class_weights: auto  # or provide a list of class weights if knowntrainer:

trainer:

  epochs: 50
  batch_size: 64
  optimizer:
    type: adamw
    beat1: 0.9
  learning_rate: 0.001

backend:
  type: ray
  processor:
    type: dask
  trainer:
    use_gpu: true
    num_workers: 4
    resources_per_worker:
      CPU: 4
      GPU: 1

