#input_features:
#  - name: DateIndex
#    type: date
#    format: 'yyyy-MM-dd HH:mm:ss'
#
#  - name: Close
#    type: timeseries
#
#output_features:
#  - name: Close_next
#    type: numerical
#    column: Close
#    preprocessing:
#      horizon: 2
#
#combiner:
#  type: concat
#  flatten_inputs: true
#
#training:
#  epochs: 10
#
#training_data:
#  file: 'test_data.csv'
#  preprocessing:
#    categorical_features_preprocessing:
#      datetime:
#        missing_value_strategy: fill_with_const
#        fill_value: '1970-01-01 00:00:00'
#    numerical_features_preprocessing:
#      Close:
#        missing_value_strategy: fill_with_const
#        fill_value: 0
#
input_features:
  - name: DateIndex
    type: date
    format: 'yyyy-MM-dd HH:mm:ss'
  - name: Close
    type: timeseries

output_features:
  - name: Close_next
    type: numerical
    column: Close
    preprocessing:
      horizon: 2

combiner:
  type: concat
  flatten_inputs: true

model:
  type: lstm
  layers:
    - units: 64
      activation: relu
    - units: 32
      activation: relu

training:
  epochs: 10

training_data:
  file: 'test_data.csv'
  preprocessing:
    categorical_features_preprocessing:
      datetime:
        missing_value_strategy: fill_with_const
        fill_value: '1970-01-01 00:00:00'
    numerical_features_preprocessing:
      Close:
        missing_value_strategy: fill_with_const
        fill_value: 0

output_directory: 'model'

callbacks:
  - early_stopping:
      type: improvement
      metric: val_loss
      threshold: 0
      early_stopping_criteria: less
