input_features:
 -
  name: text
  type: category
output_features:
  -
    name: confirmed_cases
    type: category

  -
    name: recovered_cases
    type: category

  -
    name: deaths
    type: category
