input_features:
    -
        name: image_path
        type: image
        encoder: resnet
        preprocessing:
            resize_method: interpolate
            width: 128
            height: 128

output_features:
    -
        name: label
        type: category

training:
    batch_size: 8
    epochs: 2
