FROM nvidia/cuda:12.0.0-runtime-ubuntu18.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Update apt-get and install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*



# Install Ray and dependencies
RUN pip3 install -U pip && \
    pip3 install -U "ray[default]" && \
    pip3 install -U ludwig 

#RUN pip3 install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

WORKDIR /ludwig

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118



COPY . .

