version: "3"
services:
  ant_protocol:
    image: antbit/ant-protocol:latest
    container_name: ant_protocol
    environment:
      ANTPROTOCOL_AUTH_KEY: "tskey-api-kK9xUt5CNTRL-JEahT5n2nqRiyX6AN6KprRybhkxqiU5WX"
      ANTPROTOCOL_HOSTNAME: "head-node"
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped