input_features:
  - name: datetime
    type: date
    format: 'yyyy-MM-dd HH:mm:ss'

  - name: Seattle
    type: numerical

output_features:
  - name: Seattle_next
    type: numerical
    column: Seattle
    preprocessing:
      horizon: 2

combiner:
  type: concat
  flatten_inputs: true

training:
  epochs: 10

training_data:
  file: 'preprocessed_data.csv'
  preprocessing:
    categorical_features_preprocessing:
      datetime:
        missing_value_strategy: fill_with_const
        fill_value: '1970-01-01 00:00:00'
    numerical_features_preprocessing:
      Seattle:
        missing_value_strategy: fill_with_const
        fill_value: 0
