input_features:
  - name: datetime
    type: date
   # format: '%m/%d/%Y %H:%M'
  - name: Seattle
    type: timeseries
    preprocessing:
      window_size: 10
    #encoder:
    #  type: passthrough
    #  input_shape: [45253]  # Adjust the shape based on your actual input data


output_features:
  - name: Seattle_next
    type: numerical
    column: Seattle
    preprocessing:
      horizon: 2

combiner:
  type: concat
  flatten_inputs: true

#preprocessing:
#  split:
#    type: datetime
#    column: datetime

training:
  batch_size: 16
  epochs: 50
  early_stop: 5
